config/routes.rb
Rails.application.routes.draw do
  
  resources :pictures

  resources :albums
  
  

  devise_for :users
  root "profiles#home"
  
  
  get 'image_new', to: 'images#new'
  get 'images/view_images', :to=>'images#view_images'
  get 'profiles/home', :to=>'profiles#home'
  get 'profiles/user_list', :to=>'profiles#user_list'
  get 'friendships/notifications', :to=>'friendships#notifications'
  get 'friendships/accept_friendship', :to=>'friendships#accept_friendship'
  get 'friendships/request_friendship', :to=>'friendships#request_friendship'
  delete 'friendships/destroy_friendship', :to=>'friendships#destroy_friendship'
  

  resources :comments  
  resources :friendships
  resources :profiles
  resources :images
  resources :posts
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :pictures
  belongs_to :user
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post  
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :user
  belongs_to :friend, :class => 'User'
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  belongs_to :profile
  belongs_to :pictures
  
  
  has_attached_file :avatar, :styles=>{:medium=>"300*300>", :thumb=>"100*100>", :gallery=>"300*900>"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  has_many :images
  
  accepts_nested_attributes_for :images
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_one :image
  accepts_nested_attributes_for :image
  has_many :comments
end

app/models/profile.rb
class Profile < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  has_many :posts
  has_one :profile
  has_many :albums
  has_many :friendships
  has_many :friends, :through => :friendships
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    puts "%%%%%%%%%%%%%%%%%%%%%%%%"
    puts params
    puts "%%%%%%%%%%%%%%%%%%%%%%%%%"
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = params[:id]
    @albums_pictures = Album.where(:id=>params[:id])
    @album_pics = Picture.where(:album_id=> @albums_pictures)
    @all_album_pics = Image.where(:picture_id=>@album_pics)
  end

  # GET /albums/new
  def new
    puts "%%%%%%%%%%%%%%%%%%%%%%%%"
    puts params
    puts "%%%%%%%%%%%%%%%%%%%%%%%%%"
    
    @album = Album.new
    
    
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    puts "*************************"
    puts params
    puts "************************"
    @album = Album.new(album_params)
    @album.user_id = current_user.id

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_path, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:user_id, :title)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @pics=Image.new
  end
  
  def create
    p "*************************************"
    p params
    @pics=Image.create(new_image)
    redirect_to profiles_home_path  
  end
  
  def edit
    p "################################"
    p params
    
    @edit_image=Image.find(params[:id])
  end
  
  def update
    p params
    
    @edit_image=Image.find(params[:id])
    @edit_image.update_attributes(edit_image)
    redirect_to profiles_home_path
  end
  
  def destroy
    Image.find(params[:id]).destroy
    redirect_to profiles_home_path 
  end
  
  def view_images
    @view_pic=Image.all
  end
  
  private
  def new_image
    params.require(:image).permit(:avatar,:avatar_file_name) 
  end
  
  def edit_image
    params.require(:image).permit(:avatar)
  end
   
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!
	def new
		@posts = Post.new
		
		

		@posts.image = Image.new
	end
	def create
		
		@posts = Post.new(posts_params)
		@posts.user_id = current_user.id
		@posts.save!   
        
	end
	
private

	def posts_params
		params.require(:post).permit(:post,image_attributes: [:avatar])
	end
end
                                                                                                                                                                                                                                                                             

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Friendspractice" %></title>
    
    
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->


    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    
    
    <%= render 'shared/navigation' %>
    
    <%= bootstrap_flash %>
    
    <%= render 'shared/sidebar_left' %>    
          
    <%= yield %>

    
    
    
    
    
   
      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/shared/_navigation.html.erb
<div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Friendspractice</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav" style="float: right">        
            
             <% if user_signed_in? %>
                   <li  style="float:right"; class="dropdown">
                <a href="#" data-toggle="dropdown" class="dropdown-toggle">Profile <b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="">Profile</a></li>
                    <li><%= link_to "Edit" , edit_profile_path(current_user.id) %></li>                    
                </ul>
            </li>
                
                <li style="float:right;"> <%= link_to "Logout" , destroy_user_session_path ,:method => "delete" %> </li>
                <li style="float:right;"> <%= current_user.email %> </li>                   
             <% else %>
                <li style="float:right;"> <%= link_to "SignIn" , new_user_session_path %></li>
                <li style="float:right;"> <%= link_to "SignUp" , new_user_registration_path %> </li>
             <% end %>
          </ul>
        </div>
      </div>
    </div>

app/views/shared/_sidebar_left.html.erb
<div class="col-md-2 side-bar-left">
  <div class="row">
    <div id="navigation">
      <h3>Navigation</h3><br><br>
      <div id="posts">
        <%= link_to "Posts", profiles_home_path %>
      </div><br><br>
      <div id="gallery">
        <%= link_to "Gallery", albums_path %>
      </div><br><br>
      <div id="profile">
        <label>Profile</label>
      </div><br><br>
      <div id="users">
        <%= link_to "Users", profiles_user_list_path %>
      </div>   <br><br>
      <div id="friends">
        <%= link_to "Friends", friendships_path %>
      </div><br><br>
      <div id="friends">
        <%= link_to "Notifications", friendships_notifications_path %>
      </div><br><br>
    </div>
  </div>
</div>


<style>
  .side-bar-left{
    height: auto;
    border-right: 1px solid #1D2939;
    border-bottom: 1px solid #1D2939;
    background-color: #1D2939;
    height: 500px;
    color: white;
    border-radius: 5px;
    opacity: 0.8;
    
  }
  #navigation{
    margin-left: 20px;
    font-size: 15px;
  }


</style>