config/routes.rb
Rails.application.routes.draw do
  
  resources :pictures

  resources :albums
  
  

  devise_for :users
  root "profiles#home"
  
  
  get 'image_new', to: 'images#new'
  get 'images/view_images', :to=>'images#view_images'
  get 'profiles/home', :to=>'profiles#home'
  get 'profiles/user_list', :to=>'profiles#user_list'
  get 'friendships/notifications', :to=>'friendships#notifications'
  get 'friendships/accept_friendship', :to=>'friendships#accept_friendship'
  get 'friendships/request_friendship', :to=>'friendships#request_friendship'
  delete 'friendships/destroy_friendship', :to=>'friendships#destroy_friendship'
  

  resources :comments  
  resources :friendships
  resources :profiles
  resources :images
  resources :posts
  

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :pictures
  belongs_to :user
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :set_album, only: [:show, :edit, :update, :destroy]

  # GET /albums
  # GET /albums.json
  def index
    puts "%%%%%%%%%%%%%%%%%%%%%%%%"
    puts params
    puts "%%%%%%%%%%%%%%%%%%%%%%%%%"
    @albums = Album.all
  end

  # GET /albums/1
  # GET /albums/1.json
  def show
    @album = params[:id]
    @albums_pictures = Album.where(:id=>params[:id])
    @album_pics = Picture.where(:album_id=> @albums_pictures)
    @all_album_pics = Image.where(:picture_id=>@album_pics)
  end

  # GET /albums/new
  def new
    puts "%%%%%%%%%%%%%%%%%%%%%%%%"
    puts params
    puts "%%%%%%%%%%%%%%%%%%%%%%%%%"
    
    @album = Album.new
    
    
  end

  # GET /albums/1/edit
  def edit
  end

  # POST /albums
  # POST /albums.json
  def create
    puts "*************************"
    puts params
    puts "************************"
    @album = Album.new(album_params)
    @album.user_id = current_user.id

    respond_to do |format|
      if @album.save
        format.html { redirect_to albums_path, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /albums/1
  # PATCH/PUT /albums/1.json
  def update
    respond_to do |format|
      if @album.update(album_params)
        format.html { redirect_to @album, notice: 'Album was successfully updated.' }
        format.json { render :show, status: :ok, location: @album }
      else
        format.html { render :edit }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /albums/1
  # DELETE /albums/1.json
  def destroy
    @album.destroy
    respond_to do |format|
      format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_album
      @album = Album.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def album_params
      params.require(:album).permit(:user_id, :title)
    end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_form.html.erb
<div class="col-md-5">
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class=>"form-control",:style=>"width: 205px" %>
    <%= hidden_field_tag :us1er_id, current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/albums/edit.html.erb
<h1>Editing Album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>

app/views/albums/index.html.erb
<div class="col-md-5" id="gallery-index">
<p id="notice"><%= notice %></p>

<h1>Listing Albums</h1>

<br>

<%= link_to 'New Album', new_album_path %><br><br>


<% @albums.each do |all_albums| %>
 <div><%=link_to all_albums.title, new_picture_path(:album_id=>all_albums.id) %><%= all_albums.id %></div>
 
 <div><%= link_to 'All Pics', album_path(:id=>all_albums.id) %></div><br>
<%end%>




</div>

<style>
 #gallery-index{
  margin-left: 20px;
 }
</style>

app/views/albums/new.html.erb
<h1>New Album</h1>

<%= render 'form' %>

<%= link_to 'Back', albums_path %>

app/views/albums/show.html.erb
<div class="col-md-9">
<div class="col-md-12 mb50">
   <h3>Gallery</h3>   
</div>
<br><br>

<%= link_to "upload image", new_picture_path(:album_id=>@album) %>

<p id="notice"><%= notice %></p>



<div id="wrapper">
 <div class="slider-wrapper theme-default">
  <div class="ribbon"></div>
  <div id="slider" class="ramblingSlider">
   <% @all_album_pics.each do |pics| %>
     <%= image_tag pics.avatar.url(:medium) %> alt="image1"/>     
  <%end%>
   
  </div>
 </div>
</div>


<br><br><br><br><br>

<div class="row mb50">
  <% @all_album_pics.each do |pics| %>
   <div class="col-md-3">    
    <a href="#" class="img-thumbnail">  
    <span><img src="<%= pics.avatar.url(:medium) %>", class="img-responsive"></span>      
    </a>
   </div> 
      <%end%>
</div>
<br>


  <br>
<br>
<div>
<%= link_to 'Edit', edit_album_path(@album) %> |
<%= link_to 'Back', albums_path %>
</div>
</div>
<script>
  $(window).load(function(){
    
    var name = 'directionNav';
    $('#slider').ramblingSlider({'effect': 'sliceFadeRight'});    
        
  });
</script>