config/routes.rb
Rails.application.routes.draw do
  
  resources :pictures

  resources :albums
  
  

  devise_for :users
  root "profiles#home"
  
  
  get 'image_new', to: 'images#new'
  get 'images/view_images', :to=>'images#view_images'
  get 'profiles/home', :to=>'profiles#home'
  get 'profiles/user_list', :to=>'profiles#user_list'
  get 'friendships/notifications', :to=>'friendships#notifications'
  get 'friendships/accept_friendship', :to=>'friendships#accept_friendship'
  get 'friendships/request_friendship', :to=>'friendships#request_friendship'
  delete 'friendships/destroy_friendship', :to=>'friendships#destroy_friendship'
  

  resources :comments  
  resources :friendships
  resources :profiles
  resources :images
  resources :posts
  

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  belongs_to :album
  has_many :images
  
  accepts_nested_attributes_for :images
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
    @album_id = params[:album_id]
    @picture.images.build
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    puts "##########"
    puts params
    puts "#########"
    
    @picture = Picture.new(picture_params)
    @picture.album_id = params[:album_id]

    puts @picture.album_id.inspect
    
    respond_to do |format|
      if @picture.save
        format.html { redirect_to @picture, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:album_id, :caption, :description,images_attributes: [:avatar])
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.erb
<div class="col-md-5">
<%= form_for @picture , :html => { :multipart => true } do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.fields_for :images do |pic| %>
    <%= pic.file_field :avatar %>
    <%= hidden_field_tag :album_id, @album_id %>
  <%end%>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="col-md-5">
<p id="notice"><%= notice %></p>

<h1>Listing Pictures</h1>


<br>

<%= link_to 'New Picture', new_picture_path %>
</div>

app/views/pictures/new.html.erb
<div style="border: 1px solid red">
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Album:</strong>
  <%= @picture.album_id %>
</p>

<p>
  <strong>Caption:</strong>
  <%= @picture.caption %>
</p>

<p>
  <strong>Description:</strong>
  <%= @picture.description %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>


<%= link_to 'Albums', albums_path %>