config/routes.rb
Rails.application.routes.draw do
  
  resources :pictures

  resources :albums
  
  

  devise_for :users
  root "profiles#home"
  
  
  get 'image_new', to: 'images#new'
  get 'images/view_images', :to=>'images#view_images'
  get 'profiles/home', :to=>'profiles#home'
  get 'profiles/user_list', :to=>'profiles#user_list'
  get 'friendships/notifications', :to=>'friendships#notifications'
  get 'friendships/accept_friendship', :to=>'friendships#accept_friendship'
  get 'friendships/request_friendship', :to=>'friendships#request_friendship'
  delete 'friendships/destroy_friendship', :to=>'friendships#destroy_friendship'
  

  resources :comments  
  resources :friendships
  resources :profiles
  resources :images
  resources :posts
  

end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :post
  belongs_to :profile
  belongs_to :pictures
  
  
  has_attached_file :avatar, :styles=>{:medium=>"300*300>", :thumb=>"100*100>", :gallery=>"300*900>"}
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
  
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def new
    @pics=Image.new
  end
  
  def create
    p "*************************************"
    p params
    @pics=Image.create(new_image)
    redirect_to profiles_home_path  
  end
  
  def edit
    p "################################"
    p params
    
    @edit_image=Image.find(params[:id])
  end
  
  def update
    p params
    
    @edit_image=Image.find(params[:id])
    @edit_image.update_attributes(edit_image)
    redirect_to profiles_home_path
  end
  
  def destroy
    Image.find(params[:id]).destroy
    redirect_to profiles_home_path 
  end
  
  def view_images
    @view_pic=Image.all
  end
  
  private
  def new_image
    params.require(:image).permit(:avatar,:avatar_file_name) 
  end
  
  def edit_image
    params.require(:image).permit(:avatar)
  end
   
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_image_upload.html.erb
<%= form_for @pics , :html=> {:multipart=>true} do |f| %>
   <%= f.file_field :avatar, {:class=>"form-control"} %>
   <%= f.submit %>
   
<%end%>

app/views/images/create.html.erb
<%= image_tag @view_pic.avatar(:medium) %>

app/views/images/edit.html.erb
<%= form_for @edit_image do |f| %>
   <%= f.file_field :avatar, {:class=>"form-control"} %>
   <%= f.submit %>
   
<%end%>

app/views/images/new.html.erb
<%= render 'image_upload' %>

app/views/images/view_images.html.erb
<script>
  $('.hovering').hide();
</script>



<%= link_to "new image", new_image_path %>


<% @view_pic.each do |pic| %>
<%= image_tag pic.avatar(:medium) %><br>
<div class="hovering">
   <%= link_to "edit", edit_image_path(pic.id) %> |
   <%= link_to "delete", image_path(pic.id), method: :'delete' %>

   </div>
<%end%>